<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "samples".
 *
 * @property int $id
 * @property string $message
 *
 */
abstract class Sample extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%samples}}';
    }

    public function rules()
    {
        return [
            'trim' => [['message'], 'trim'],
            'message_string' => [['message'], 'string'],
        ];
    }
}
