<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "animals".
 *
 * @property int $id
 * @property int $name
 * @property string $g desc for g
 * @property string $g2 changed comment on g2 col
 * @property string $g3 the comment on g3 col remains same
 * @property int $g4 data type changes but comment remains same
 * @property string $new_col new col added
 *
 */
abstract class Animal extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%animals}}';
    }

    public function rules()
    {
        return [
            'trim' => [['g', 'g2', 'g3', 'new_col'], 'trim'],
            'name_integer' => [['name'], 'integer'],
            'g_string' => [['g'], 'string'],
            'g2_string' => [['g2'], 'string'],
            'g3_string' => [['g3'], 'string'],
            'g4_integer' => [['g4'], 'integer'],
            'new_col_string' => [['new_col'], 'string'],
        ];
    }
}
