<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "animals".
 *
 * @property int $id
 * @property string $name
 *
 */
abstract class Animal extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%animals}}';
    }

    public function rules()
    {
        return [
            'trim' => [['name'], 'trim'],
            'name_string' => [['name'], 'string'],
        ];
    }

    public function getInvoice()
    {
        return $this->hasOne(\app\models\Invoice::class, ['animal_id' => 'id'])->inverseOf('animal');
    }
}
