<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "fruits".
 *
 * @property int $id
 * @property string $name
 *
 */
abstract class Fruit extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%fruits}}';
    }

    public function rules()
    {
        return [
            'trim' => [['name'], 'trim'],
            'name_string' => [['name'], 'string'],
        ];
    }

    # belongs to relation
    public function getInvoice()
    {
        return $this->hasOne(\app\models\Invoice::class, ['fruit_id' => 'id']);
    }
}
