<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "invoices".
 *
 * @property int $id
 * @property int $reference_invoice_id
 * @property int $reference_invoice_2_id
 * @property int $user_id
 * @property int $user_2_id
 * @property int $fruit_id
 * @property int $animal_id
 *
 * @property \app\models\Invoice $referenceInvoice
 * @property \app\models\Invoice $referenceInvoice2
 * @property \app\models\User $user
 * @property \app\models\User $user2
 * @property \app\models\Fruit $fruit
 * @property \app\models\Animal $animal
 */
abstract class Invoice extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%invoices}}';
    }

    public function rules()
    {
        return [
            'reference_invoice_id_integer' => [['reference_invoice_id'], 'integer'],
            'reference_invoice_id_exist' => [['reference_invoice_id'], 'exist', 'targetRelation' => 'referenceInvoice'],
            'reference_invoice_2_id_integer' => [['reference_invoice_2_id'], 'integer'],
            'reference_invoice_2_id_exist' => [['reference_invoice_2_id'], 'exist', 'targetRelation' => 'referenceInvoice2'],
            'user_id_integer' => [['user_id'], 'integer'],
            'user_id_exist' => [['user_id'], 'exist', 'targetRelation' => 'user'],
            'user_2_id_integer' => [['user_2_id'], 'integer'],
            'user_2_id_exist' => [['user_2_id'], 'exist', 'targetRelation' => 'user2'],
            'fruit_id_integer' => [['fruit_id'], 'integer'],
            'fruit_id_exist' => [['fruit_id'], 'exist', 'targetRelation' => 'fruit'],
            'animal_id_integer' => [['animal_id'], 'integer'],
            'animal_id_exist' => [['animal_id'], 'exist', 'targetRelation' => 'animal'],
        ];
    }

    public function getReferenceInvoice()
    {
        return $this->hasOne(\app\models\Invoice::class, ['id' => 'reference_invoice_id']);
    }

    public function getReferenceInvoice2()
    {
        return $this->hasOne(\app\models\Invoice::class, ['id' => 'reference_invoice_2_id']);
    }

    public function getUser()
    {
        return $this->hasOne(\app\models\User::class, ['id' => 'user_id']);
    }

    public function getUser2()
    {
        return $this->hasOne(\app\models\User::class, ['id' => 'user_2_id']);
    }

    public function getFruit()
    {
        return $this->hasOne(\app\models\Fruit::class, ['id' => 'fruit_id']);
    }

    public function getAnimal()
    {
        return $this->hasOne(\app\models\Animal::class, ['id' => 'animal_id']);
    }

    public function getInvoice()
    {
        return $this->hasOne(\app\models\Invoice::class, ['reference_invoice_id' => 'id'])->inverseOf('reference_invoice');
    }

    public function getInvoice2()
    {
        return $this->hasOne(\app\models\Invoice::class, ['reference_invoice_2_id' => 'id'])->inverseOf('reference_invoice_2');
    }
}
