<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "invoices".
 *
 * @property int $id
 * @property int $reference_invoice_id
 * @property int $reference_invoice_2_id
 * @property int $user_id
 * @property int $user_2_id
 *
 * @property \app\models\Invoice $referenceInvoice
 * @property \app\models\Invoice $referenceInvoice2
 * @property \app\models\Invoice $user
 * @property \app\models\Invoice $user2
 */
abstract class Invoice extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%invoices}}';
    }

    public function rules()
    {
        return [
            'reference_invoice_id_integer' => [['reference_invoice_id'], 'integer'],
            'reference_invoice_id_exist' => [['reference_invoice_id'], 'exist', 'targetRelation' => 'ReferenceInvoice'],
            'reference_invoice_2_id_integer' => [['reference_invoice_2_id'], 'integer'],
            'reference_invoice_2_id_exist' => [['reference_invoice_2_id'], 'exist', 'targetRelation' => 'ReferenceInvoice2'],
            'user_id_integer' => [['user_id'], 'integer'],
            'user_id_exist' => [['user_id'], 'exist', 'targetRelation' => 'User'],
            'user_2_id_integer' => [['user_2_id'], 'integer'],
            'user_2_id_exist' => [['user_2_id'], 'exist', 'targetRelation' => 'User2'],
        ];
    }

    public function getReferenceInvoice()
    {
        return $this->hasOne(\app\models\Invoice::class, ['id' => 'reference_invoice_id']);
    }

    public function getReferenceInvoice2()
    {
        return $this->hasOne(\app\models\Invoice::class, ['id' => 'reference_invoice_2_id']);
    }

    public function getUser()
    {
        return $this->hasOne(\app\models\Invoice::class, ['id' => 'user_id']);
    }

    public function getUser2()
    {
        return $this->hasOne(\app\models\Invoice::class, ['id' => 'user_2_id']);
    }
}
