<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "users".
 *
 * @property int $id
 * @property string $name
 *
 * @property array|\app\models\Invoice[] $invoices
 * @property array|\app\models\Invoice[] $user2Invoices
 */
abstract class User extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%users}}';
    }

    public function rules()
    {
        return [
            'trim' => [['name'], 'trim'],
            'name_string' => [['name'], 'string'],
        ];
    }

    # inverse relation
    public function getInvoices()
    {
        return $this->hasMany(\app\models\Invoice::class, ['user_id' => 'id']);
    }

    # inverse relation
    public function getUser2Invoices()
    {
        return $this->hasMany(\app\models\Invoice::class, ['user_2_id' => 'id']);
    }
}
