<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * desc
 *
 * @property int $id
 * @property string $name
 *
 * @property array|\app\models\Routing[] $routings
 */
abstract class D123 extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%d123s}}';
    }

    public function rules()
    {
        return [
            'trim' => [['name'], 'trim'],
            'name_string' => [['name'], 'string'],
        ];
    }

    # inverse relation
    public function getRoutings()
    {
        return $this->hasMany(\app\models\Routing::class, ['d123_id' => 'id']);
    }
}
