<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * desc
 *
 * @property int $id
 * @property string $name
 * @property string $shortName
 * @property string $postCode
 *
 */
abstract class Address extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%addresses}}';
    }

    public function rules()
    {
        return [
            'trim' => [['name', 'shortName', 'postCode'], 'trim'],
            'shortName_postCode_unique' => [['shortName', 'postCode'], 'unique', 'targetAttribute' => [
                'shortName',
                'postCode',
            ]],
            'name_string' => [['name'], 'string', 'max' => 64],
            'shortName_string' => [['shortName'], 'string', 'max' => 64],
            'postCode_string' => [['postCode'], 'string', 'max' => 64],
        ];
    }
}
