<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * x-db-default-expression test
 *
 * @property string $ts
 * @property string $ts2
 * @property string $ts3
 * @property string $ts4
 * @property string $ts5
 * @property string $ts6
 * @property string $d
 * @property string $d2
 * @property string $d3
 * @property string $ts7
 *
 */
abstract class Fruit extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%fruits}}';
    }

    public function rules()
    {
        return [
            'trim' => [['ts', 'ts2', 'ts3', 'ts4', 'ts5', 'ts6', 'd', 'd2', 'd3', 'ts7'], 'trim'],
            'ts_datetime' => [['ts'], 'datetime', 'format' => 'php:Y-m-d H:i:s'],
            'ts_default' => [['ts'], 'default', 'value' => new \yii\db\Expression("(CURRENT_TIMESTAMP)")],
            'ts2_datetime' => [['ts2'], 'datetime', 'format' => 'php:Y-m-d H:i:s'],
            'ts2_default' => [['ts2'], 'default', 'value' => '2011-11-11 00:00:00'],
            'ts3_datetime' => [['ts3'], 'datetime', 'format' => 'php:Y-m-d H:i:s'],
            'ts3_default' => [['ts3'], 'default', 'value' => '2022-11-11 00:00:00'],
            'ts4_string' => [['ts4'], 'string'],
            'ts4_default' => [['ts4'], 'default', 'value' => '2022-11-11 00:00:00'],
            'ts5_string' => [['ts5'], 'string'],
            'ts5_default' => [['ts5'], 'default', 'value' => new \yii\db\Expression("(CURRENT_TIMESTAMP)")],
            'ts6_string' => [['ts6'], 'string'],
            'ts6_default' => [['ts6'], 'default', 'value' => '2000-11-11 00:00:00'],
            'd_date' => [['d'], 'date', 'format' => 'php:Y-m-d'],
            'd_default' => [['d'], 'default', 'value' => new \yii\db\Expression("(CURRENT_DATE + INTERVAL 1 YEAR)")],
            'd2_string' => [['d2'], 'string'],
            'd2_default' => [['d2'], 'default', 'value' => new \yii\db\Expression("(CURRENT_DATE + INTERVAL 1 YEAR)")],
            'd3_string' => [['d3'], 'string'],
            'd3_default' => [['d3'], 'default', 'value' => 'text default'],
            'ts7_date' => [['ts7'], 'date', 'format' => 'php:Y-m-d'],
            'ts7_default' => [['ts7'], 'default', 'value' => new \yii\db\Expression("(CURRENT_DATE + INTERVAL 1 YEAR)")],
        ];
    }
}
