<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * A store's description
 *
 * @property int $id
 * @property string $name
 *
 * @property array|\app\models\Pet[] $pets
 */
abstract class Store extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%stores}}';
    }

    public function rules()
    {
        return [
            'trim' => [['name'], 'trim'],
            'required' => [['name'], 'required'],
            'name_string' => [['name'], 'string'],
        ];
    }

    # inverse relation
    public function getPets()
    {
        return $this->hasMany(\app\models\Pet::class, ['store_id' => 'id']);
    }
}
