<?php

/**
 * Table for Alldbdatatype
 */
class m200000_000000_create_table_alldbdatatypes extends \yii\db\Migration
{
    public function safeUp()
    {
        $this->createTable('{{%alldbdatatypes}}', [
            'id' => $this->bigPrimaryKey(),
            0 => '"string_col" varchar NOT NULL',
            1 => '"varchar_col" varchar NOT NULL',
            2 => '"text_col" text NOT NULL',
            3 => '"text_col_array" text[] NOT NULL',
            4 => '"varchar_4_col" varchar(4) NOT NULL',
            5 => '"varchar_5_col" varchar(5) NOT NULL',
            6 => '"char_4_col" char(4) NOT NULL',
            7 => '"char_5_col" char NOT NULL',
            8 => '"char_6_col" char NOT NULL',
            9 => '"char_7_col" char(6) NOT NULL',
            10 => '"char_8_col" char NOT NULL DEFAULT \'d\'',
            11 => '"decimal_col" decimal(12,3) NOT NULL',
            12 => '"bytea_col_2" bytea NOT NULL',
            13 => '"bit_col" bit NOT NULL',
            14 => '"bit_2" bit(1) NOT NULL',
            15 => '"bit_3" bit(64) NOT NULL',
            16 => '"ti" smallint NOT NULL',
            17 => '"int2_col" int2 NOT NULL',
            18 => '"smallserial_col" smallserial NOT NULL',
            19 => '"serial2_col" serial2 NOT NULL',
            20 => '"si_col" smallint NOT NULL',
            21 => '"si_col_2" smallint NOT NULL',
            22 => '"bi" bigint NOT NULL',
            23 => '"bi2" int8 NOT NULL',
            24 => '"int4_col" int4 NOT NULL',
            25 => '"bigserial_col" bigserial NOT NULL',
            26 => '"bigserial_col_2" serial8 NOT NULL',
            27 => '"int_col" int NOT NULL',
            28 => '"int_col_2" integer NOT NULL',
            29 => '"numeric_col" numeric NOT NULL',
            30 => '"numeric_col_2" numeric(10) NOT NULL',
            31 => '"numeric_col_3" numeric(10,2) NOT NULL',
            32 => '"double_p_2" double precision NOT NULL',
            33 => '"double_p_3" double precision NOT NULL',
            34 => '"real_col" real NOT NULL',
            35 => '"float4_col" float4 NOT NULL',
            36 => '"date_col" date NOT NULL',
            37 => '"time_col" time NOT NULL',
            38 => '"time_col_2" time with time zone NOT NULL',
            39 => '"time_col_3" time without time zone NOT NULL',
            40 => '"time_col_4" time(3) without time zone NOT NULL',
            41 => '"timetz_col" timetz NOT NULL',
            42 => '"timetz_col_2" timetz(3) NOT NULL',
            43 => '"timestamp_col" timestamp NOT NULL',
            44 => '"timestamp_col_2" timestamp with time zone NOT NULL',
            45 => '"timestamp_col_3" timestamp without time zone NOT NULL',
            46 => '"timestamp_col_4" timestamp(3) without time zone NOT NULL',
            47 => '"timestamptz_col" timestamptz NOT NULL',
            48 => '"timestamptz_col_2" timestamptz(3) NOT NULL',
            49 => '"date2" date NOT NULL',
            50 => '"timestamp_col_z" timestamp NOT NULL',
            51 => '"bit_varying" bit varying NOT NULL',
            52 => '"bit_varying_n" bit varying(8) NOT NULL',
            53 => '"bit_varying_n_2" varbit NOT NULL',
            54 => '"bit_varying_n_3" varbit(3) NOT NULL',
            55 => '"bool_col" boolean NOT NULL',
            56 => '"bool_col_2" bool NOT NULL',
            57 => '"box_col" box NOT NULL',
            58 => '"character_col" character NOT NULL',
            59 => '"character_n" character(12) NOT NULL',
            60 => '"character_varying" character varying NOT NULL',
            61 => '"character_varying_n" character varying(12) NOT NULL',
            62 => '"json_col" json NOT NULL',
            63 => '"jsonb_col" jsonb NOT NULL',
            64 => '"json_col_def" json NOT NULL DEFAULT \'[]\'',
            65 => '"json_col_def_2" json NOT NULL DEFAULT \'[]\'',
            66 => '"bytea_def" bytea NOT NULL DEFAULT \'the bytea blob default\'',
            67 => '"text_def" text NOT NULL DEFAULT \'the text\'',
            68 => '"json_def" json NOT NULL DEFAULT \'{"a":"b"}\'',
            69 => '"jsonb_def" jsonb NOT NULL DEFAULT \'{"ba":"bb"}\'',
            70 => '"cidr_col" cidr NOT NULL',
            71 => '"circle_col" circle NOT NULL',
            72 => '"date_col_z" date NOT NULL',
            73 => '"float8_col" float8 NOT NULL',
            74 => '"inet_col" inet NOT NULL',
            75 => '"interval_col" interval NOT NULL',
            76 => '"interval_col_2" interval year NOT NULL',
            77 => '"interval_col_3" interval day to second(3) NOT NULL',
            78 => '"line_col" line NOT NULL',
            79 => '"lseg_col" lseg NOT NULL',
            80 => '"macaddr_col" macaddr NOT NULL',
            81 => '"money_col" money NOT NULL',
            82 => '"path_col" path NOT NULL',
            83 => '"pg_lsn_col" pg_lsn NOT NULL',
            84 => '"point_col" point NOT NULL',
            85 => '"polygon_col" polygon NOT NULL',
            86 => '"serial_col" serial NOT NULL',
            87 => '"serial4_col" serial4 NOT NULL',
            88 => '"tsquery_col" tsquery NOT NULL',
            89 => '"tsvector_col" tsvector NOT NULL',
            90 => '"txid_snapshot_col" txid_snapshot NOT NULL',
            91 => '"uuid_col" uuid NOT NULL',
            92 => '"xml_col" xml NOT NULL',
        ]);
    }

    public function safeDown()
    {
        $this->dropTable('{{%alldbdatatypes}}');
    }
}
