<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "addresses".
 *
 * @property int $id
 * @property string $name
 *
 */
abstract class Address extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%addresses}}';
    }

    public function rules()
    {
        return [
            'trim' => [['name'], 'trim'],
            'name_string' => [['name'], 'string'],
        ];
    }

    # belongs to relation
    public function getHuman()
    {
        return $this->hasOne(\app\models\Human::class, ['address_id' => 'id']);
    }
}
