<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "humans".
 *
 * @property int $id
 * @property string $name
 * @property int $address_id
 *
 * @property \app\models\Address $address
 */
abstract class Human extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%humans}}';
    }

    public function rules()
    {
        return [
            'trim' => [['name'], 'trim'],
            'name_string' => [['name'], 'string'],
            'address_id_integer' => [['address_id'], 'integer'],
            'address_id_exist' => [['address_id'], 'exist', 'targetRelation' => 'address'],
        ];
    }

    public function getAddress()
    {
        return $this->hasOne(\app\models\Address::class, ['id' => 'address_id']);
    }
}
