<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "addresses".
 *
 * @property int $id
 * @property string $shortName
 * @property string $postCode
 *
 */
abstract class Address extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%addresses}}';
    }

    public function rules()
    {
        return [
            'trim' => [['shortName', 'postCode'], 'trim'],
            'shortName_string' => [['shortName'], 'string'],
            'postCode_string' => [['postCode'], 'string', 'max' => 64],
        ];
    }

    # belongs to relation
    public function getFoo()
    {
        return $this->hasOne(\app\models\Foo::class, ['address_id' => 'id']);
    }

    # belongs to relation
    public function getBar()
    {
        return $this->hasOne(\app\models\Bar::class, ['task_id' => 'id']);
    }

    # belongs to relation
    public function getBar2()
    {
        return $this->hasOne(\app\models\Bar::class, ['related_task_id' => 'id']);
    }
}
