<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "bars".
 *
 * @property int $id
 * @property int $address_id
 * @property int $related_address_id
 *
 * @property \app\models\Address $address
 * @property \app\models\Address $relatedAddress
 */
abstract class Bar extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%bars}}';
    }

    public function rules()
    {
        return [
            'address_id_integer' => [['address_id'], 'integer'],
            'address_id_exist' => [['address_id'], 'exist', 'targetRelation' => 'address'],
            'related_address_id_integer' => [['related_address_id'], 'integer'],
            'related_address_id_exist' => [['related_address_id'], 'exist', 'targetRelation' => 'relatedAddress'],
        ];
    }

    public function getAddress()
    {
        return $this->hasOne(\app\models\Address::class, ['id' => 'address_id']);
    }

    public function getRelatedAddress()
    {
        return $this->hasOne(\app\models\Address::class, ['id' => 'related_address_id']);
    }
}
