<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "bars".
 *
 * @property int $id
 * @property int $task_id
 * @property int $related_task_id
 *
 * @property \app\models\Address $task
 * @property \app\models\Address $relatedTask
 */
abstract class Bar extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%bars}}';
    }

    public function rules()
    {
        return [
            'task_id_integer' => [['task_id'], 'integer'],
            'task_id_exist' => [['task_id'], 'exist', 'targetRelation' => 'task'],
            'related_task_id_integer' => [['related_task_id'], 'integer'],
            'related_task_id_exist' => [['related_task_id'], 'exist', 'targetRelation' => 'relatedTask'],
        ];
    }

    public function getTask()
    {
        return $this->hasOne(\app\models\Address::class, ['id' => 'task_id']);
    }

    public function getRelatedTask()
    {
        return $this->hasOne(\app\models\Address::class, ['id' => 'related_task_id']);
    }
}
