<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "invoices".
 *
 * @property int $id The PK
 * @property int $reference_invoice_id This field is only set on invoices of type "cancellation_invoice"
 *
 * @property \app\models\Invoice $referenceInvoice
 */
abstract class Invoice extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%invoices}}';
    }

    public function rules()
    {
        return [
            'reference_invoice_id_integer' => [['reference_invoice_id'], 'integer'],
            'reference_invoice_id_exist' => [['reference_invoice_id'], 'exist', 'targetRelation' => 'ReferenceInvoice'],
        ];
    }

    public function getReferenceInvoice()
    {
        return $this->hasOne(\app\models\Invoice::class, ['id' => 'reference_invoice_id']);
    }
}
