<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * user account
 *
 * @property int $id
 * @property string $name account name
 *
 * @property array|\app\models\E123[] $e123s
 * @property array|\app\models\E123[] $account2E123s
 * @property array|\app\models\E123[] $account3E123s
 */
abstract class Account extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%accounts}}';
    }

    public function rules()
    {
        return [
            'trim' => [['name'], 'trim'],
            'required' => [['name'], 'required'],
            'name_string' => [['name'], 'string', 'max' => 40],
        ];
    }

    // inverse relation
    public function getE123s()
    {
        return $this->hasMany(\app\models\E123::class, ['account_id' => 'id']);
    }

    // inverse relation
    public function getAccount2E123s()
    {
        return $this->hasMany(\app\models\E123::class, ['account_2_id' => 'id']);
    }

    // inverse relation
    public function getAccount3E123s()
    {
        return $this->hasMany(\app\models\E123::class, ['account_3_id' => 'id']);
    }
}
