<?php
/**
 * @var \cebe\yii2openapi\lib\items\DbModel $model
 * @var string $namespace
 * @var string $relationNamespace
 **/
use cebe\yii2openapi\lib\items\AttributeRelation;
use yii\helpers\Inflector;
use yii\helpers\VarDumper;

$allCoveredClasses = array_merge(
    array_map(fn($r) => $r->getClassName(), (array)$model->relations),
    array_map(fn($r) => $r->relatedClassName, (array)$model->many2many),
    array_map(fn($r) => $r->getClassName(), (array)$model->nonDbRelations)
);
/**
 * Resolve inverse relation method names from the FK column name of the other model.
 * Relations already covered by $model->relations, many2many, or nonDbRelations are skipped.
 * Relations from models declared with "x-table: false" are skipped (no real table, no FK).
 *
 * Naming logic (model being generated = e.g. "Lead", $modelSnake = "lead"):
 *   1. Take the FK column name from the other model (e.g. Order.customer_lead_id)
 *   2. Strip trailing "_id"              → "customer_lead"
 *   3. Strip trailing "_<modelSnake>"    → "customer"
 *   4. If a prefix remains, prepend it to the pluralized class name:
 *        "customer" + "Orders"           → getCustomerOrders()
 *      If no prefix remains (plain FK like "lead_id"):
 *        "" + "Orders"                   → getOrders()
 *
 * Examples: Order has three FK columns pointing to Lead ($model->name = "Lead"):
 *
 *   FK column (on Order)      | generated on Order      | generated on Lead (inverse)
 *   --------------------------|-------------------------|----------------------------
 *   lead_id                   | getLead()               | getOrders()
 *   customer_lead_id          | getCustomerLead()       | getCustomerOrders()
 *   billing_lead_id           | getBillingLead()        | getBillingOrders()
 */
$modelSnake = Inflector::underscore($model->name);
$inverseRelations = array_map(function (AttributeRelation $relation) use ($modelSnake): array {
    $inverseMethod = $relation->getMethod() === 'hasOne' ? 'hasMany' : 'hasOne';
    $classBase = $inverseMethod === 'hasMany' ? Inflector::pluralize($relation->getCamelName()) : $relation->getCamelName();
    $fkBase = preg_replace('/_id$/', '', $relation->getForeignName());
    $prefix = preg_replace('/_?' . preg_quote($modelSnake, '/') . '$/', '', $fkBase);
    return [
        'relation' => $relation,
        'inverseMethod' => $inverseMethod,
        'inverseName' => $prefix !== '' ? Inflector::camelize($prefix) . $classBase : $classBase,
    ];
}, array_filter(
    (array)$model->belongsToRelations,
    fn(AttributeRelation $r) => !in_array($r->getClassName(), $allCoveredClasses) && $r->getTableName() !== ''
));
?>
<?= '<?php' ?>


/**
 * This file is generated by Gii, do not change manually!
 */

namespace <?= $namespace ?>;

/**
 *<?= $model->getModelClassDescription() ?>

 *
<?php foreach ($model->dbAttributes() as $attribute): ?>
 * @property <?= $attribute->getPropertyAnnotation() ?>

<?php endforeach; ?>
 *
<?php foreach ($model->relations as $relationName => $relation): ?>
<?php if ($relation->isHasOne()):?>
 * @property \<?= trim($relationNamespace, '\\') ?>\<?= $relation->getClassName() ?> $<?= Inflector::variablize($relation->getName()) ?>
<?php else:?>
 * @property array|\<?= trim($relationNamespace, '\\') ?>\<?= $relation->getClassName() ?>[] $<?= Inflector::variablize($relation->getName()) ?>
<?php endif?>

<?php endforeach; ?>
<?php foreach ($model->nonDbRelations as $relationName => $relation): ?>
<?php if ($relation->isHasOne()):?>
 * @property \<?= trim($relationNamespace, '\\') ?>\<?= $relation->getClassName() ?> $<?= Inflector::variablize($relation->getName()) ?>
<?php else:?>
 * @property array|\<?= trim($relationNamespace, '\\') ?>\<?= $relation->getClassName() ?>[] $<?= Inflector::variablize($relation->getName()) ?>
<?php endif?>

<?php endforeach; ?>
<?php foreach ($model->many2many as $relation): ?>
 * @property array|\<?= trim($relationNamespace, '\\') ?>\<?= $relation->relatedClassName ?>[] $<?= Inflector::variablize($relation->name) ?>

<?php endforeach; ?>
<?php foreach ($inverseRelations as $inverse): ?>
<?php if ($inverse['inverseMethod'] === 'hasOne'):?>
 * @property \<?= trim($relationNamespace, '\\') ?>\<?= $inverse['relation']->getClassName() ?> $<?= Inflector::variablize($inverse['inverseName']) ?>

<?php else:?>
 * @property array|\<?= trim($relationNamespace, '\\') ?>\<?= $inverse['relation']->getClassName() ?>[] $<?= Inflector::variablize($inverse['inverseName']) ?>

<?php endif?>
<?php endforeach; ?>
 */
abstract class <?= $model->getClassName() ?> extends \yii\db\ActiveRecord
{
<?php if ($scenarios = $model->getScenarios()):
foreach ($scenarios as $scenario): ?>
    /**
     *<?= $scenario['description'] ?>

     */
    public const <?= $scenario['const'] ?> = '<?= $scenario['name'] ?>';

<?php endforeach; ?>
<?php endif ?>
<?php if (count($model->virtualAttributes())):?>
    protected $virtualAttributes = ['<?=implode("', '", array_map(function ($attr) {
    return $attr->columnName;
}, $model->virtualAttributes()))?>'];

<?php foreach ($model->virtualAttributes() as $attribute): ?>
    /**
     * @var <?=$attribute->phpType.PHP_EOL?>
    */
    public $<?= $attribute->columnName ?>;

<?php endforeach; ?>
<?php endif;?>
    public static function tableName()
    {
        return <?= var_export($model->getTableAlias()) ?>;
    }
<?php if ($scenarios): ?>

    /**
     * Automatically generated scenarios from the model 'x-scenarios'.
     * @return array a list of scenarios and the corresponding active attributes.
     */
    public function scenarios()
    {
        $parentScenarios = parent::scenarios();

        /**
         * Each scenario is assigned attributes as in the 'default' scenario.
         * The advantage is that the scenario can be used immediately.
         * This can be overridden in the child model if needed.
         */
        $default = $parentScenarios[self::SCENARIO_DEFAULT];

        return [
<?php foreach ($scenarios as $scenario): ?>
            self::<?= $scenario['const'] ?> => $default,
<?php endforeach; ?>
            /**
             * The 'default' scenario and all scenarios mentioned in the rules() using 'on' and 'except'
             * are automatically included in the scenarios() function for the model.
             */
            ...$parentScenarios,
        ];
    }
<?php endif;?>
<?php if (count($model->virtualAttributes())):?>

    public function attributes()
    {
        return array_merge(parent::attributes(), $this->virtualAttributes);
    }

    public function afterFind()
    {
        parent::afterFind();
        foreach ($this->virtualAttributes as $attr) {
            $this->$attr = $this->getAttribute($attr);
        }
    }
<?php endif;?>

    public function rules()
    {
        return <?=$model->getValidationRules()?>;
    }
<?php foreach ($model->relations as $relationName => $relation): ?>

    public function get<?= $relation->getCamelName() ?>()
    {
        return $this-><?= $relation->getMethod() ?>(\<?= trim($relationNamespace, '\\') ?>\<?= $relation->getClassName() ?>::class, <?php
            echo $relation->linkToString()?>)<?= $relation->getInverse() ? '->inverseOf(\''.$relation->getInverse().'\')' : '' ?>;
    }
<?php endforeach; ?>
<?php foreach ($model->many2many as $relation): ?>

    public function get<?= $relation->getCamelName() ?>()
    {
        return $this->hasMany(\<?= trim($relationNamespace, '\\') ?>\<?= $relation->relatedClassName ?>::class, <?php
            echo $relation->linkToString($relation->link)?>)
<?php if (!$relation->hasViaModel):?>
                    ->viaTable(<?=VarDumper::export($relation->viaTableName)?>, <?=$relation->linkToString($relation->viaLink)?>);
<?php else:?>
                    ->via('<?=lcfirst($relation->getViaRelationName())?>');
<?php endif;?>
    }
<?php endforeach; ?>
<?php foreach ($model->nonDbRelations as $nonDbRelation): ?>

    abstract public function get<?= $nonDbRelation->getCamelName() ?>(): \yii\db\ActiveQuery;
<?php endforeach; ?>
<?php foreach ($inverseRelations as $inverse): ?>

    // inverse relation
    public function get<?= $inverse['inverseName'] ?>()
    {
        return $this-><?= $inverse['inverseMethod'] ?>(\<?= trim($relationNamespace, '\\') ?>\<?= $inverse['relation']->getClassName() ?>::class, <?php
    echo $inverse['relation']->linkToString() ?>);
    }
<?php endforeach; ?>
}
