<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "bank_account_transactions".
 *
 * @property int $id
 *
 * @property \app\models\Booking $booking
 */
abstract class BankAccountTransaction extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%bank_account_transactions}}';
    }

    public function rules()
    {
        return [];
    }

    abstract public function getBooking(): \yii\db\ActiveQuery;
}
