<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "bookings".
 *
 * @property int $id
 * @property int $bank_account_transaction_id
 *
 * @property \app\models\BankAccountTransaction $bankAccountTransaction
 */
abstract class Booking extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%bookings}}';
    }

    public function rules()
    {
        return [
            'bank_account_transaction_id_integer' => [['bank_account_transaction_id'], 'integer'],
            'bank_account_transaction_id_exist' => [['bank_account_transaction_id'], 'exist', 'targetRelation' => 'bankAccountTransaction'],
        ];
    }

    public function getBankAccountTransaction()
    {
        return $this->hasOne(\app\models\BankAccountTransaction::class, ['id' => 'bank_account_transaction_id']);
    }
}
