<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "companies".
 *
 * @property int $id
 * @property string $name
 *
 * @property array|\app\models\Lead[] $leads
 */
abstract class Company extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%companies}}';
    }

    public function rules()
    {
        return [
            'trim' => [['name'], 'trim'],
            'name_string' => [['name'], 'string'],
        ];
    }

    # inverse relation
    public function getLeads()
    {
        return $this->hasMany(\app\models\Lead::class, ['company_id' => 'id']);
    }
}
