<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "invoices".
 *
 * @property int $id
 *
 * @property array|\app\models\Order[] $orders
 */
abstract class Invoice extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%invoices}}';
    }

    public function rules()
    {
        return [];
    }

    # inverse relation
    public function getOrders()
    {
        return $this->hasMany(\app\models\Order::class, ['invoice_id' => 'id']);
    }
}
