<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "leads".
 *
 * @property int $id
 * @property string $name
 * @property int $company_id
 *
 * @property \app\models\Company $company
 * @property array|\app\models\Order[] $orders
 * @property array|\app\models\Order[] $customerOrders
 * @property array|\app\models\Order[] $billingOrders
 */
abstract class Lead extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%leads}}';
    }

    public function rules()
    {
        return [
            'trim' => [['name'], 'trim'],
            'name_string' => [['name'], 'string'],
            'company_id_integer' => [['company_id'], 'integer'],
            'company_id_exist' => [['company_id'], 'exist', 'targetRelation' => 'company'],
        ];
    }

    public function getCompany()
    {
        return $this->hasOne(\app\models\Company::class, ['id' => 'company_id']);
    }

    # inverse relation
    public function getOrders()
    {
        return $this->hasMany(\app\models\Order::class, ['lead_id' => 'id']);
    }

    # inverse relation
    public function getCustomerOrders()
    {
        return $this->hasMany(\app\models\Order::class, ['customer_lead_id' => 'id']);
    }

    # inverse relation
    public function getBillingOrders()
    {
        return $this->hasMany(\app\models\Order::class, ['billing_lead_id' => 'id']);
    }
}
