<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "orders".
 *
 * @property int $id
 * @property int $lead_id
 * @property int $customer_lead_id
 * @property int $billing_lead_id
 * @property int $invoice_id
 *
 * @property \app\models\Lead $lead
 * @property \app\models\Lead $customerLead
 * @property \app\models\Lead $billingLead
 * @property \app\models\Invoice $invoice
 */
abstract class Order extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%orders}}';
    }

    public function rules()
    {
        return [
            'lead_id_integer' => [['lead_id'], 'integer'],
            'lead_id_exist' => [['lead_id'], 'exist', 'targetRelation' => 'lead'],
            'customer_lead_id_integer' => [['customer_lead_id'], 'integer'],
            'customer_lead_id_exist' => [['customer_lead_id'], 'exist', 'targetRelation' => 'customerLead'],
            'billing_lead_id_integer' => [['billing_lead_id'], 'integer'],
            'billing_lead_id_exist' => [['billing_lead_id'], 'exist', 'targetRelation' => 'billingLead'],
            'invoice_id_integer' => [['invoice_id'], 'integer'],
            'invoice_id_exist' => [['invoice_id'], 'exist', 'targetRelation' => 'invoice'],
        ];
    }

    public function getLead()
    {
        return $this->hasOne(\app\models\Lead::class, ['id' => 'lead_id']);
    }

    public function getCustomerLead()
    {
        return $this->hasOne(\app\models\Lead::class, ['id' => 'customer_lead_id']);
    }

    public function getBillingLead()
    {
        return $this->hasOne(\app\models\Lead::class, ['id' => 'billing_lead_id']);
    }

    public function getInvoice()
    {
        return $this->hasOne(\app\models\Invoice::class, ['id' => 'invoice_id']);
    }
}
