<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * Schema for testing faker stub generation for JSON columns with array/object types. Each property triggers a specific code path in FakerStubResolver (fakeForArray / fakeForObject) that previously returned a broken faker expression.
 *
 * @property int $id
 * @property array $arr_no_items
 * @property array $obj_no_props
 * @property array $arr_obj_no_props
 *
 */
abstract class JsonArrObj extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%json_arr_obj}}';
    }

    public function rules()
    {
        return [
            'safe' => [['arr_no_items', 'obj_no_props', 'arr_obj_no_props'], 'safe'],
        ];
    }
}
