<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "invoices".
 *
 * @property int $id
 * @property string $vat_rate
 *
 */
abstract class Invoice extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%invoices}}';
    }

    public function rules()
    {
        return [
            'required' => [['vat_rate'], 'required'],
            'vat_rate_string' => [['vat_rate'], 'string'],
            'vat_rate_in' => [['vat_rate'], 'in', 'range' => [
                'standard',
                'none',
            ]],
            'vat_rate_default' => [['vat_rate'], 'default', 'value' => 'standard'],
        ];
    }
}
