<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "posts".
 *
 * @property int $id
 * @property string $content
 * @property int $user
 *
 * @property \app\models\User $userRel
 */
abstract class Post extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%posts}}';
    }

    public function rules()
    {
        return [
            'trim' => [['content'], 'trim'],
            'content_string' => [['content'], 'string'],
            'user_integer' => [['user'], 'integer'],
            'user_exist' => [['user'], 'exist', 'targetRelation' => 'userRel'],
        ];
    }

    public function getUserRel()
    {
        return $this->hasOne(\app\models\User::class, ['id' => 'user']);
    }
}
