<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "menus".
 *
 * @property int $id
 * @property string $name
 * @property int $parent_id
 *
 * @property \app\models\Menu $parent
 * @property array|\app\models\Menu[] $childes
 */
abstract class Menu extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%menus}}';
    }

    public function rules()
    {
        return [
            'trim' => [['name'], 'trim'],
            'required' => [['name'], 'required'],
            'name_string' => [['name'], 'string', 'min' => 3, 'max' => 100],
            'parent_id_integer' => [['parent_id'], 'integer'],
            'parent_id_exist' => [['parent_id'], 'exist', 'targetRelation' => 'parent'],
        ];
    }

    public function getParent()
    {
        return $this->hasOne(\app\models\Menu::class, ['id' => 'parent_id']);
    }

    public function getChildes()
    {
        return $this->hasMany(\app\models\Menu::class, ['parent_id' => 'id']);
    }
}
