<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "deliveries".
 *
 * @property int $id
 * @property string $title
 *
 * @property array|\app\models\Webhook[] $redeliveryOfWebhooks
 * @property array|\app\models\Webhook[] $rdAbc2Webhooks
 */
abstract class Delivery extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%deliveries}}';
    }

    public function rules()
    {
        return [
            'trim' => [['title'], 'trim'],
            'title_string' => [['title'], 'string'],
        ];
    }

    # inverse relation
    public function getRedeliveryOfWebhooks()
    {
        return $this->hasMany(\app\models\Webhook::class, ['redelivery_of' => 'id']);
    }

    # inverse relation
    public function getRdAbc2Webhooks()
    {
        return $this->hasMany(\app\models\Webhook::class, ['rd_abc_2' => 'id']);
    }
}
