<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "addresses".
 *
 * @property int $id
 * @property int $user_id
 *
 * @property \app\models\User $user
 */
abstract class Address extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%addresses}}';
    }

    public function rules()
    {
        return [
            'user_id_integer' => [['user_id'], 'integer'],
            'user_id_exist' => [['user_id'], 'exist', 'targetRelation' => 'user'],
        ];
    }

    public function getUser()
    {
        return $this->hasOne(\app\models\User::class, ['id' => 'user_id']);
    }
}
