<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "users".
 *
 * @property int $id
 *
 */
abstract class User extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%users}}';
    }

    public function rules()
    {
        return [];
    }

    # belongs to relation
    public function getAddress()
    {
        return $this->hasOne(\app\models\Address::class, ['user_id' => 'id']);
    }
}
