<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "pristines".
 *
 * @property integer $id
 * @property string $name
 * @property integer $fruit_id
 *
 */
abstract class Pristine extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%pristines}}';
    }

    public function rules()
    {
        return [
            'trim' => [['name'], 'trim'],
            'name_string' => [['name'], 'string', 'max' => 151],
            'fruit_id_integer' => [['fruit_id'], 'integer'],
        ];
    }
}
