<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "payments".
 *
 * @property int $id
 * @property int $amount
 * @property string $currency
 *
 */
abstract class Payment extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%payments}}';
    }

    public function rules()
    {
        return [
            'trim' => [['currency'], 'trim'],
            'currency_string' => [['currency'], 'string'],
        ];
    }
}
