<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * The User
 *
 * @property int $id
 * @property string $login
 * @property string $email
 * @property string $password
 * @property string $role
 * @property int $flags
 * @property string $created_at
 *
 */
abstract class User extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%v2_users}}';
    }

    public function rules()
    {
        return [
            'trim' => [['login', 'email', 'password', 'created_at'], 'trim'],
            'flags_default' => [['flags'], 'default', 'value' => 0],
            'required' => [['login', 'email', 'password'], 'required'],
            'login_string' => [['login'], 'string'],
            'email_string' => [['email'], 'string', 'max' => 255],
            'email_email' => [['email'], 'email'],
            'password_string' => [['password'], 'string'],
            'role_string' => [['role'], 'string'],
            'role_in' => [['role'], 'in', 'range' => [
                'admin',
                'editor',
                'reader',
            ]],
            'flags_integer' => [['flags'], 'integer'],
            'created_at_datetime' => [['created_at'], 'datetime', 'format' => 'php:Y-m-d H:i:s'],
            'login_unique' => [['login'], 'unique'],
            'email_unique' => [['email'], 'unique'],
        ];
    }

    # belongs to relation
    public function getPost()
    {
        return $this->hasOne(\app\models\Post::class, ['created_by_id' => 'id']);
    }

    # belongs to relation
    public function getComment()
    {
        return $this->hasOne(\app\models\Comment::class, ['user_id' => 'id']);
    }
}
