<?php

/**
 * This file is generated by Gii, do not change manually!
 */

namespace app\models\base;

/**
 * This is the model class for table "tasks".
 *
 * @property int $id
 * @property string $title
 *
 */
abstract class Task extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return '{{%tasks}}';
    }

    public function rules()
    {
        return [
            'trim' => [['title'], 'trim'],
            'title_string' => [['title'], 'string'],
        ];
    }
}
